### ISSUE TITLE
"a1.0.10, a1.0.5 & a1.0.4" throw "java.lang.IllegalArgumentException" upon creating a new world.

### ISSUE THREAD

**Issue by sojlabjoi** [sojlabjoi/AlphacraftLauncher#4]
Launcher version: 1.2.0723_pre1

This does not happen all the time. Sometimes when creating a new world, the error does not occur, but it does occur often when creating a new world, or when joining a pre-made world.

### Alpha v1.0.10
```
java.lang.IllegalArgumentException: Comparison method violates its general contract!
	at java.util.TimSort.mergeHi(TimSort.java:868)
	at java.util.TimSort.mergeAt(TimSort.java:485)
	at java.util.TimSort.mergeCollapse(TimSort.java:408)
	at java.util.TimSort.sort(TimSort.java:214)
	at java.util.TimSort.sort(TimSort.java:173)
	at java.util.Arrays.sort(Arrays.java:660)
	at java.util.Collections.sort(Collections.java:223)
	at e.a(SourceFile:926)
	at ht.b(SourceFile:359)
	at ht.a(SourceFile:301)
	at net.minecraft.client.Minecraft.run(SourceFile:602)
	at java.lang.Thread.run(Thread.java:748)
```

### Alpha v1.0.5
```
java.lang.IllegalArgumentException: Comparison method violates its general contract!
	at java.util.TimSort.mergeHi(TimSort.java:868)
	at java.util.TimSort.mergeAt(TimSort.java:485)
	at java.util.TimSort.mergeCollapse(TimSort.java:408)
	at java.util.TimSort.sort(TimSort.java:214)
	at java.util.TimSort.sort(TimSort.java:173)
	at java.util.Arrays.sort(Arrays.java:660)
	at java.util.Collections.sort(Collections.java:223)
	at e.a(SourceFile:920)
	at gy.b(SourceFile:359)
	at gy.a(SourceFile:301)
	at y.run(SourceFile:598)
	at java.lang.Thread.run(Thread.java:748)
```

### Alpha v1.0.4
```
java.lang.IllegalArgumentException: Comparison method violates its general contract!
	at java.util.TimSort.mergeHi(TimSort.java:868)
	at java.util.TimSort.mergeAt(TimSort.java:485)
	at java.util.TimSort.mergeCollapse(TimSort.java:408)
	at java.util.TimSort.sort(TimSort.java:214)
	at java.util.TimSort.sort(TimSort.java:173)
	at java.util.Arrays.sort(Arrays.java:660)
	at java.util.Collections.sort(Collections.java:223)
	at m.a(SourceFile:920)
	at cd.b(SourceFile:359)
	at cd.a(SourceFile:301)
	at ax.run(SourceFile:588)
	at java.lang.Thread.run(Thread.java:748)
```

**Comment by sojlabjoi** [comment]
Seems to be fixed in version "1.2.0823_pre1" and I don't know why or how.
